### ISSUE TITLE
Trailforks integration

### ISSUE THREAD

**Issue by Estebiu** [hishizuka/pizero_bikecomputer#14]
Trailforks it's an amazing source for different type of trails, and I wonder if it could be included in your project. Anyway, did you think about making a commercial product out of this? I mean, designing the PCB and the case, and sell it?

**Comment by hishizuka** [comment]
Hi @Estebiu , currently I have no plans to integrate Trailforks, because my environment does not seem to be suitable. I don't have a MTB or gravel bike and Trailforks are not popular in Japan where I live.

With a distant goal I would like to make a kit. And of course a PCB. I am not satisfied with the current hardware configuration and think that even just changing the display to 4.4", for example, would create an experience unlike anything I have seen before.
